"""Georgian Sign Language interpreter prototype."""

FEATURE_VERSION = "landmarks_v3_body_relative_30x702"
NUM_FRAMES = 30
HAND_FEATURE_SIZE = 126
HAND_BODY_FEATURE_SIZE = 126
POSE_FEATURE_SIZE = 99
FEATURE_SIZE = HAND_FEATURE_SIZE + HAND_BODY_FEATURE_SIZE + POSE_FEATURE_SIZE
MODEL_FEATURE_SIZE = FEATURE_SIZE * 2
